import {
  Home,
  UserPlus,
  UserCheck,
  UserX,
  UsersIcon,
  CreditCard,
  Plus,
  CheckCircle,
  XCircle,
  GraduationCap,
  Video,
  UploadCloud,
  FileText,
  BadgePercent,
  PhoneCall,
  Projector,
  Image,
  Group,
  Star,
  ScrollText,
  Handshake,
  Trophy,
  ThumbsUp,
  Users,
  GalleryHorizontal,
  PartyPopper,
  AlertCircle,
  Building2,
  Newspaper,
  Settings,
  LogOut,
  MessageCircle,
  LayoutList,
  Send,
  BookUser,
  CircleFadingPlus,
  BadgePlus,
  QrCode,
  PointerOffIcon,
} from "lucide-react";

export const menuItems = [
  {
    path: "/dashboard",
    icon: Home,
    label: "Dashboard",
    active: true,
    roles: ["Admin", "Employee"],
  },
  {
    key: "students",
    icon: UserPlus,
    label: "Registrations",
    hasSubmenu: true,
    roles: ["Admin", "Employee"],
    submenu: [
      {
        path: "/AddStudent",
        label: "Add Student",
        icon: Plus,
        roles: ["Admin", "Employee"],
      },
      {
        key: "new",
        path: "/new",
        label: "New",
        icon: BadgePlus,
        roles: ["Admin", "Employee"],
      },
      {
        key: "accepted",
        path: "/accepted",
        label: "Accepted",
        icon: UserCheck,
        roles: ["Admin", "Employee"],
      },
      {
        key: "rejected",
        path: "/rejected",
        label: "Rejected",
        icon: UserX,
        roles: ["Admin", "Employee"],
      },
      {
        key: "all",
        path: "/all-students",
        label: "All Students",
        icon: UsersIcon,
        roles: ["Admin", "Employee"],
      },
    ],
  },

  {
    key: "fees",
    icon: CreditCard,
    label: "Fee Payments",
    hasSubmenu: true,
    roles: ["Admin", "Employee"],
    submenu: [
      {
        path: "/pay-fee",
        label: "Pay Fee",
        icon: CreditCard,
        roles: ["Admin", "Employee"],
      },
      {
        key: "new",
        path: "/new-fee",
        label: "New",
        icon: Plus,
        roles: ["Admin", "Employee"],
      },
      {
        key: "accepted",
        path: "/accepted-fee",
        label: "Accepted",
        icon: CheckCircle,
        roles: ["Admin", "Employee"],
      },
      {
        key: "rejected",
        path: "/rejected-fee",
        label: "Rejected",
        icon: XCircle,
        roles: ["Admin", "Employee"],
      },
    ],
  },
  {
    key: "attendance",
    icon: CheckCircle,
    label: "Manage Attendance",
    hasSubmenu: true,
    roles: ["Admin", "Employee", "Intern"],
    submenu: [
      {
        path: "/attendance-marking",
        icon: BookUser,
        label: "Attendance Marking",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/attendance-viwe",
        icon: BookUser,
        label: "Attendance Viwe",
        roles: ["Admin", "Employee", "Intern"],
      },
    ],
  },
  {
    key: "setting",
    icon: Settings,
    label: "Manage Settings",
    hasSubmenu: true,
    roles: ["Admin"],
    submenu: [
      {
        path: "/tranning",
        icon: BookUser,
        label: "Tranning Type",
        roles: ["Admin", "Employee"],
      },

      {
        path: "/technology",
        icon: BookUser,
        label: "Technology",
        roles: ["Admin", "Employee"],
      },
      {
        path: "/education",
        icon: BookUser,
        label: "Education",
        roles: ["Admin", "Employee"],
      },
      {
        path: "/collages",
        icon: BookUser,
        label: "Collages",
        roles: ["Admin", "Employee"],
      },

      {
        path: "/manage-hr",
        icon: BookUser,
        label: "Manage Hr",
        roles: ["Admin", "Employee"],
      },
      {
        path: "/qr-code",
        icon: QrCode,
        label: "Qr Code",
        roles: ["Admin"],
      },
      {
        path: "/employee",
        icon: QrCode,
        label: "Manage Employee",
        roles: ["Admin"],
      },
      {
        path: "/teacher",
        icon: QrCode,
        label: "Manage Teacher",
        roles: ["Admin", "Employee"],
      },
      {
        path: "/branchs",
        icon: QrCode,
        label: "Manage Branchs",
        roles: ["Admin", "Employee"],
      },
      {
        path: "/batchs",
        icon: QrCode,
        label: "Manage Batchs",
        roles: ["Admin", "Employee"],
      },
    ],
  },
  {
    key: "Jobs",
    icon: CheckCircle,
    label: "Manage Jobs",
    hasSubmenu: true,
    roles: ["Admin", "Employee", "Intern"],
    submenu: [
      {
        path: "/create-company",
        icon: BookUser,
        label: "Manage Company",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/create-jobs",
        icon: BookUser,
        label: "Manage Jobs",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/student-assing-job",
        icon: BookUser,
        label: "Student Assing Jobs",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/job-applications",
        icon: BookUser,
        label: "Job Applications",
        roles: ["Admin", "Employee", "Intern"],
      },
    ],
  },
  {
    key: "Reports",
    icon: CheckCircle,
    label: "Reports",
    hasSubmenu: true,
    roles: ["Admin", "Employee", "Intern"],
    submenu: [
      {
        path: "/reg-reoprts",
        icon: BookUser,
        label: "Registration",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/fee-reports",
        icon: BookUser,
        label: "Fee",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/absent-stu-reports",
        icon: BookUser,
        label: "Absent Student",
        roles: ["Admin", "Employee", "Intern"],
      },
      {
        path: "/attendenc-reports",
        icon: BookUser,
        label: "Attendenc Reports",
        roles: ["Admin", "Employee", "Intern"],
      },
    ],
  },
  {
    path: "/assignments",
    icon: PointerOffIcon,
    label: "Manage Assignments",
    roles: ["Admin", "Employee"],
  },
  {
    path: "/profile",
    icon: PointerOffIcon,
    label: "Profile",
    roles: ["Admin", "Employee"],
  },
  {
    path: "/",
    icon: LogOut,
    label: "Log Out",
  },
];
